patreon: Promoping

custom:
  - "https://www.paypal.com/donate/?hosted_button_id=SCCD4N72ZGXTW"
  - "https://promoping.pt"
  - "https://www.instagram.com/_julissz_/"
  - "https://github.com/juliareboucasleite/PromoPing"
