server:
  port: ${LAVALINK_PORT:2333}
  address: 127.0.0.1
  http2:
    enabled: false

lavalink:
  server:
    password: ${LAVALINK_PASSWORD:promoping-lavalink}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      rotation: true
      distortion: true
      channelMix: true
      lowPass: true
      pluginFilters: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
    gc-warnings: true
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - WEBEMBEDDED
      - TVHTML5_SIMPLY

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  file:
    path: "./logs"
  level:
    root: INFO
    lavalink: INFO
