const pg = require("pg");

const { Pool, Client, types } = pg;

types.setTypeParser(1700, (val) => (val === null ? null : parseFloat(val)));
types.setTypeParser(20, (val) => {
    if (val === null) return null;
    const n = Number(val);
    return Number.isSafeInteger(n) ? n : val;
});

const poolCache = new Map();

function getPool(config = {}) {
    const explicitUser = config.user && config.user !== "root" ? config.user : undefined;
    const explicitPort = config.port && Number(config.port) !== 3306 ? Number(config.port) : undefined;
    const normalized = {
        host: config.host || process.env.DB_HOST || "localhost",
        user: explicitUser || process.env.DB_USER || "postgres",
        password: config.password ?? process.env.DB_PASSWORD ?? "",
        database: config.database || process.env.DB_NAME || "papv5",
        port: explicitPort || Number(process.env.DB_PORT || 5432),
    };

    const key = JSON.stringify(normalized);
    if (!poolCache.has(key)) {
        poolCache.set(key, new Pool({
            ...normalized,
            max: 10,
            idleTimeoutMillis: 30000,
            connectionTimeoutMillis: 5000,
        }));
    }

    return poolCache.get(key);
}

function convertPlaceholders(sql) {
    if (typeof sql !== "string" || !sql.includes("?")) return sql;

    let out = "";
    let inSingle = false;
    let inDouble = false;
    let index = 0;

    for (let i = 0; i < sql.length; i += 1) {
        const ch = sql[i];
        if (!inDouble && ch === "'") {
            inSingle = !inSingle;
            out += ch;
            continue;
        }
        if (!inSingle && ch === '"') {
            inDouble = !inDouble;
            out += ch;
            continue;
        }
        if (!inSingle && !inDouble && ch === "?") {
            index += 1;
            out += `$${index}`;
            continue;
        }
        out += ch;
    }

    return out;
}

function normalizeMysqlSqlForPg(sql) {
    if (typeof sql !== "string") return sql;

    return sql
        .replace(/`/g, '"')
        .replace(/\bDATABASE\(\)/gi, "current_schema()")
        .replace(/\bCURDATE\(\)/gi, "CURRENT_DATE")
        .replace(/\bNOW\(\)/gi, "CURRENT_TIMESTAMP")
        .replace(/\bint\(\d+\)\s+unsigned/gi, "INTEGER")
        .replace(/\bint\(\d+\)/gi, "INTEGER")
        .replace(/\btinyint\(1\)/gi, "BOOLEAN")
        .replace(/\bdatetime\b/gi, "TIMESTAMP")
        .replace(/\benum\((?:[^)(]+|\([^)(]*\))*\)/gi, "VARCHAR(100)")
        .replace(/\s+ON UPDATE CURRENT_TIMESTAMP/gi, "")
        .replace(/\s+COMMENT\s+'(?:[^']|'')*'/gi, "")
        .replace(/\bAUTO_INCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY")
        .replace(/\)\s*ENGINE=[\s\S]*?(?=\s*(?:;|$))/gi, ")")
        .replace(/\s+DEFAULT CHARSET=\w+/gi, "")
        .replace(/\s+CHARSET=\w+/gi, "")
        .replace(/\s+COLLATE=\w+/gi, "")
        .replace(/\s+COLLATE\s+(?:utf8mb4|utf8|latin1|ascii|binary)\w*/gi, "")
        .replace(/,\s*INDEX\s+[A-Za-z0-9_]+\s*\([^)]+\)/gi, "")
        .replace(/,\s*KEY\s+[A-Za-z0-9_]+\s*\([^)]+\)/gi, "")
        .replace(/,\s*UNIQUE KEY\s+[A-Za-z0-9_]+\s*\(([^)]+)\)/gi, ", UNIQUE ($1)")
        .replace(/SET\s+([A-Za-z_][A-Za-z0-9_]*)\./gi, "SET ");
}

function rewriteInformationSchema(sql, params, config = {}) {
    let rewrittenSql = sql;
    const rewrittenParams = [...(params || [])];

    if (/TABLE_SCHEMA\s*=\s*\?/i.test(rewrittenSql) && rewrittenParams.length > 0) {
        rewrittenSql = rewrittenSql.replace(/TABLE_SCHEMA\s*=\s*\?/i, "table_schema = current_schema()");
        const dbName = config.database || process.env.DB_NAME || "papv5";
        const firstParam = rewrittenParams[0];
        if (!firstParam || String(firstParam).toLowerCase() === String(dbName).toLowerCase()) {
            rewrittenParams.shift();
        }
    }

    return { sql: rewrittenSql, params: rewrittenParams };
}

function ensureInsertReturning(sql) {
    if (typeof sql !== "string") return sql;
    const trimmed = sql.trim();
    if (!/^insert\b/i.test(trimmed) || /\breturning\b/i.test(trimmed)) {
        return sql;
    }
    return `${trimmed.replace(/;+\s*$/, "")} RETURNING *`;
}

function extractInsertId(rows) {
    if (!Array.isArray(rows) || rows.length === 0 || !rows[0]) return 0;

    const firstRow = rows[0];
    for (const key of ["id", "Id", "ID"]) {
        if (Object.prototype.hasOwnProperty.call(firstRow, key)) {
            return firstRow[key];
        }
    }

    for (const [key, value] of Object.entries(firstRow)) {
        if (/id$/i.test(key) && (typeof value === "number" || typeof value === "string")) {
            return value;
        }
    }

    return 0;
}

// PG dobra identificadores não-quotados para minúsculas. O código mysql2 acede
// às colunas com a capitalização declarada (ex.: row.ReferenciaID). Wrap em
// Proxy case-insensitive para manter compatibilidade sem tocar nas queries.
function caseInsensitiveRow(row) {
    if (!row || typeof row !== "object") return row;
    const lowerMap = Object.create(null);
    for (const key of Object.keys(row)) {
        lowerMap[key.toLowerCase()] = key;
    }
    return new Proxy(row, {
        get(target, prop, receiver) {
            if (typeof prop === "string" && !Object.prototype.hasOwnProperty.call(target, prop)) {
                const real = lowerMap[prop.toLowerCase()];
                if (real !== undefined) return target[real];
            }
            return Reflect.get(target, prop, receiver);
        },
        has(target, prop) {
            if (prop in target) return true;
            if (typeof prop === "string") {
                return lowerMap[prop.toLowerCase()] !== undefined;
            }
            return false;
        },
    });
}

function wrapRows(rows) {
    if (!Array.isArray(rows)) return rows;
    return rows.map(caseInsensitiveRow);
}

function formatCompatResult(result) {
    const command = String(result?.command || "").toUpperCase();
    const rows = wrapRows(result?.rows ?? []);
    if (command === "SELECT") {
        return [rows, result.fields];
    }

    return [{
        affectedRows: result?.rowCount ?? 0,
        changedRows: command === "UPDATE" ? (result?.rowCount ?? 0) : 0,
        insertId: command === "INSERT" ? extractInsertId(result?.rows) : 0,
        rowCount: result?.rowCount ?? 0,
        command,
        rows,
    }, result?.fields];
}

function prepareSql(sql, params, config) {
    const rewritten = rewriteInformationSchema(sql, params, config);
    const preparedSql = ensureInsertReturning(
        normalizeMysqlSqlForPg(convertPlaceholders(rewritten.sql))
    );
    return { sql: preparedSql, params: rewritten.params };
}

function wrapClient(client, release) {
    return {
        async query(sql, params) {
            const prepared = prepareSql(sql, params);
            const result = await client.query(prepared.sql, prepared.params || []);
            return formatCompatResult(result);
        },
        async execute(sql, params) {
            const prepared = prepareSql(sql, params);
            const result = await client.query(prepared.sql, prepared.params || []);
            return formatCompatResult(result);
        },
        async beginTransaction() {
            await client.query("BEGIN");
        },
        async commit() {
            await client.query("COMMIT");
        },
        async rollback() {
            await client.query("ROLLBACK");
        },
        async end() {
            if (typeof release === "function") {
                await release();
            }
        },
        async release() {
            if (typeof release === "function") {
                await release();
            }
        },
    };
}

async function createConnection(config = {}) {
    const poolConfig = {
        host: config.host || process.env.DB_HOST || "localhost",
        user: (config.user && config.user !== "root" ? config.user : undefined) || process.env.DB_USER || "postgres",
        password: config.password ?? process.env.DB_PASSWORD ?? "",
        database: config.database || process.env.DB_NAME || "papv5",
        port: (config.port && Number(config.port) !== 3306 ? Number(config.port) : undefined) || Number(process.env.DB_PORT || 5432),
    };

    const client = new Client(poolConfig);
    await client.connect();
    return wrapClient(client, () => client.end());
}

function createPool(config = {}) {
    const pool = getPool(config);

    return {
        async query(sql, params) {
            const prepared = prepareSql(sql, params, config);
            const result = await pool.query(prepared.sql, prepared.params || []);
            return formatCompatResult(result);
        },
        async execute(sql, params) {
            const prepared = prepareSql(sql, params, config);
            const result = await pool.query(prepared.sql, prepared.params || []);
            return formatCompatResult(result);
        },
        async getConnection() {
            return await createConnection(config);
        },
        async end() {
            await pool.end();
        },
    };
}

module.exports = {
    createConnection,
    createPool,
};
