const mysql = require("./mysql2-compat");
const path = require("path");

require("dotenv").config({ path: path.join(__dirname, "../../.env") });

async function columnExists(connection, tableName, columnName) {
    const [rows] = await connection.execute(`
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = ?
          AND column_name = ?
        LIMIT 1
    `, [tableName.toLowerCase(), columnName.toLowerCase()]);

    return rows.length > 0;
}

async function ensureColumn(connection, tableName, columnName, definition) {
    if (!(await columnExists(connection, tableName, columnName))) {
        await connection.execute(`ALTER TABLE ${tableName} ADD COLUMN ${columnName} ${definition}`);
    }
}

async function ensureRenamedColumn(connection, tableName, oldName, newName) {
    const hasOld = await columnExists(connection, tableName, oldName);
    const hasNew = await columnExists(connection, tableName, newName);

    if (hasOld && !hasNew) {
        await connection.execute(`ALTER TABLE ${tableName} RENAME COLUMN ${oldName} TO ${newName}`);
    }
}

async function ensureIdentity(connection, tableName, columnName = "id") {
    const [sequenceRows] = await connection.execute(
        "SELECT pg_get_serial_sequence(?, ?) AS seq",
        [tableName.toLowerCase(), columnName.toLowerCase()]
    );

    if (!sequenceRows[0]?.seq) {
        await connection.execute(`ALTER TABLE ${tableName} ALTER COLUMN ${columnName} ADD GENERATED BY DEFAULT AS IDENTITY`);
    }

    const [maxRows] = await connection.execute(
        `SELECT COALESCE(MAX(${columnName}), 0) AS max_id FROM ${tableName}`
    );
    const [updatedSequenceRows] = await connection.execute(
        "SELECT pg_get_serial_sequence(?, ?) AS seq",
        [tableName.toLowerCase(), columnName.toLowerCase()]
    );

    if (updatedSequenceRows[0]?.seq) {
        await connection.execute(
            "SELECT setval(?, ?, false)",
            [updatedSequenceRows[0].seq, Number(maxRows[0]?.max_id || 0) + 1]
        );
    }
}

async function ensureDefault(connection, tableName, columnName, defaultExpression) {
    await connection.execute(
        `ALTER TABLE ${tableName} ALTER COLUMN ${columnName} SET DEFAULT ${defaultExpression}`
    );
}

async function ensureBooleanColumn(connection, tableName, columnName, defaultValue = false) {
    await connection.execute(`
        ALTER TABLE ${tableName}
        ALTER COLUMN ${columnName} TYPE BOOLEAN
        USING CASE
            WHEN ${columnName} IS NULL THEN ${defaultValue ? "TRUE" : "FALSE"}
            WHEN ${columnName}::text IN ('1', 'true', 'TRUE', 't', 'T', 'yes', 'YES') THEN TRUE
            ELSE FALSE
        END
    `);
    await connection.execute(
        `UPDATE ${tableName} SET ${columnName} = ${defaultValue ? "TRUE" : "FALSE"} WHERE ${columnName} IS NULL`
    );
    await ensureDefault(connection, tableName, columnName, defaultValue ? "TRUE" : "FALSE");
}

async function ensureTimestampDefault(connection, tableName, columnName) {
    await connection.execute(
        `UPDATE ${tableName} SET ${columnName} = CURRENT_TIMESTAMP WHERE ${columnName} IS NULL`
    );
    await ensureDefault(connection, tableName, columnName, "CURRENT_TIMESTAMP");
}

async function ensureIntegerDefault(connection, tableName, columnName, defaultValue = 0) {
    await connection.execute(
        `UPDATE ${tableName} SET ${columnName} = ${defaultValue} WHERE ${columnName} IS NULL`
    );
    await ensureDefault(connection, tableName, columnName, String(defaultValue));
}

async function ensureIndex(connection, indexName, tableName, expression, unique = false) {
    await connection.execute(
        `CREATE ${unique ? "UNIQUE " : ""}INDEX IF NOT EXISTS ${indexName} ON ${tableName} (${expression})`
    );
}

async function ensureHistoricoprecos(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS historicoprecos (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            ProdutoId INT NOT NULL,
            Preco DECIMAL(10, 2) NOT NULL,
            PrecoAnterior DECIMAL(10, 2) DEFAULT NULL,
            DataRegisto TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            Loja VARCHAR(255),
            Status ENUM('Ativo', 'Inativo', 'Pausado') DEFAULT 'Ativo',
            Observacoes TEXT,
            FOREIGN KEY (ProdutoId) REFERENCES produtos(Id) ON DELETE CASCADE
        )
    `);

    await ensureIdentity(connection, "historicoprecos");
    await ensureColumn(connection, "historicoprecos", "PrecoAnterior", "NUMERIC(10, 2)");
    await ensureColumn(connection, "historicoprecos", "Loja", "VARCHAR(255)");
    await ensureColumn(connection, "historicoprecos", "Status", "VARCHAR(20) DEFAULT 'Ativo'");
    await ensureColumn(connection, "historicoprecos", "Observacoes", "TEXT");
    await ensureColumn(connection, "historicoprecos", "UpdatedAt", "TIMESTAMP");
    await ensureTimestampDefault(connection, "historicoprecos", "DataRegisto");
    await ensureTimestampDefault(connection, "historicoprecos", "UpdatedAt");
    await connection.execute("UPDATE historicoprecos SET Status = 'Ativo' WHERE Status IS NULL");
    await ensureDefault(connection, "historicoprecos", "Status", "'Ativo'");
    await ensureIndex(connection, "idx_historicoprecos_produto_data", "historicoprecos", "ProdutoId, DataRegisto");
    await ensureIndex(connection, "idx_historicoprecos_dataregisto", "historicoprecos", "DataRegisto");
    await ensureIndex(connection, "idx_historicoprecos_loja", "historicoprecos", "Loja");
}

async function ensureDiscordIdColumn(connection, databaseName) {
    const [columns] = await connection.execute(`
        SELECT COLUMN_NAME
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = ? AND TABLE_NAME = 'utilizadores' AND COLUMN_NAME = 'discord_id'
    `, [databaseName]);

    if (columns.length === 0) {
        await connection.execute(`
            ALTER TABLE utilizadores
            ADD COLUMN discord_id VARCHAR(50) UNIQUE NULL
        `);
        console.log("Coluna discord_id adicionada à tabela utilizadores");
    } else {
        console.log("Coluna discord_id já existe na tabela utilizadores");
    }
}

async function ensureTwitchChannels(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS twitch_channels (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            ChannelName VARCHAR(100) NOT NULL UNIQUE,
            TwitchUserId VARCHAR(50),
            IsLive BOOLEAN DEFAULT FALSE,
            LastLiveCheck TIMESTAMP NULL,
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "twitch_channels");
    await ensureColumn(connection, "twitch_channels", "TwitchUserId", "VARCHAR(50)");
    await ensureColumn(connection, "twitch_channels", "LastLiveCheck", "TIMESTAMP NULL");
    await ensureColumn(connection, "twitch_channels", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "twitch_channels", "UpdatedAt", "TIMESTAMP");
    await ensureBooleanColumn(connection, "twitch_channels", "IsLive", false);
    await ensureTimestampDefault(connection, "twitch_channels", "CreatedAt");
    await ensureTimestampDefault(connection, "twitch_channels", "UpdatedAt");
    await ensureIndex(connection, "idx_twitch_channels_channelname", "twitch_channels", "ChannelName");
    await ensureIndex(connection, "idx_twitch_channels_islive", "twitch_channels", "IsLive");
}

async function ensureWebhookConfigs(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS webhook_configs (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            Type ENUM('github', 'twitch', 'other') NOT NULL DEFAULT 'other',
            WebhookUrl VARCHAR(500),
            Secret VARCHAR(255),
            IsActive BOOLEAN DEFAULT TRUE,
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureRenamedColumn(connection, "webhook_configs", "tipo", "type");
    await ensureIdentity(connection, "webhook_configs");
    await ensureColumn(connection, "webhook_configs", "Type", "VARCHAR(100) DEFAULT 'other'");
    await ensureColumn(connection, "webhook_configs", "WebhookUrl", "VARCHAR(500)");
    await ensureColumn(connection, "webhook_configs", "Secret", "VARCHAR(255)");
    await ensureColumn(connection, "webhook_configs", "IsActive", "BOOLEAN");
    await ensureColumn(connection, "webhook_configs", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "webhook_configs", "UpdatedAt", "TIMESTAMP");
    await connection.execute("UPDATE webhook_configs SET Type = 'other' WHERE Type IS NULL");
    await ensureDefault(connection, "webhook_configs", "Type", "'other'");
    await ensureBooleanColumn(connection, "webhook_configs", "IsActive", true);
    await ensureTimestampDefault(connection, "webhook_configs", "CreatedAt");
    await ensureTimestampDefault(connection, "webhook_configs", "UpdatedAt");
    await ensureIndex(connection, "idx_webhook_configs_type", "webhook_configs", "Type");
    await ensureIndex(connection, "idx_webhook_configs_isactive", "webhook_configs", "IsActive");
}

async function ensureCountingConfig(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS counting_config (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            GuildId VARCHAR(50) NOT NULL UNIQUE,
            ChannelId VARCHAR(50) NOT NULL,
            CurrentNumber INT DEFAULT 0,
            HighScore INT DEFAULT 0,
            LastUserId VARCHAR(50),
            LastMessageId VARCHAR(50),
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "counting_config");
    await ensureColumn(connection, "counting_config", "CurrentNumber", "INTEGER DEFAULT 0");
    await ensureColumn(connection, "counting_config", "HighScore", "INTEGER DEFAULT 0");
    await ensureColumn(connection, "counting_config", "LastUserId", "VARCHAR(50)");
    await ensureColumn(connection, "counting_config", "LastMessageId", "VARCHAR(50)");
    await ensureColumn(connection, "counting_config", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "counting_config", "UpdatedAt", "TIMESTAMP");
    await ensureIntegerDefault(connection, "counting_config", "CurrentNumber", 0);
    await ensureIntegerDefault(connection, "counting_config", "HighScore", 0);
    await ensureTimestampDefault(connection, "counting_config", "CreatedAt");
    await ensureTimestampDefault(connection, "counting_config", "UpdatedAt");
    await ensureIndex(connection, "idx_counting_config_guildid", "counting_config", "GuildId");
    await ensureIndex(connection, "idx_counting_config_channelid", "counting_config", "ChannelId");
}

async function setupDatabase() {
    console.log("Configurando banco de dados para Discord Bot...");

    const dbConfig = {
        host: process.env.DB_HOST || "localhost",
        user: process.env.DB_USER || "postgres",
        password: process.env.DB_PASSWORD || "",
        database: process.env.DB_NAME || "papv5",
        port: parseInt(process.env.DB_PORT, 10) || 5432,
    };

    let connection;

    try {
        connection = await mysql.createConnection(dbConfig);
        console.log("Conectado ao banco de dados");

        await ensureHistoricoprecos(connection);
        console.log("Tabela historicoprecos criada/ajustada");

        await ensureDiscordIdColumn(connection, dbConfig.database);

        const [existingData] = await connection.execute("SELECT COUNT(*) as count FROM historicoprecos");
        if (existingData[0].count === 0) {
            await connection.execute(`
                INSERT INTO historicoprecos (ProdutoId, Preco, PrecoAnterior, Loja, Status, Observacoes) VALUES
                (1, 299.99, 319.99, 'Amazon', 'Ativo', 'Preço atualizado via scraper'),
                (1, 319.99, 299.99, 'Amazon', 'Ativo', 'Preço aumentou'),
                (2, 199.99, 219.99, 'Fnac', 'Ativo', 'Desconto aplicado')
            `);
            console.log("Dados de exemplo inseridos");
        }

        await connection.execute(`
            UPDATE utilizadores
            SET discord_id = '123456789012345678'
            WHERE ReferenciaID = (
                SELECT ReferenciaID
                FROM utilizadores
                WHERE discord_id IS NULL
                  AND ReferenciaID <> 'ANON'
                ORDER BY DataRegisto ASC
                LIMIT 1
            )
        `);
        console.log("Usuário de teste configurado com discord_id");

        await ensureTwitchChannels(connection);
        console.log("Tabela twitch_channels criada/ajustada");

        const [existingChannel] = await connection.execute(
            "SELECT Id FROM twitch_channels WHERE ChannelName = ?",
            ["leeksxy"]
        );

        if (existingChannel.length === 0) {
            await connection.execute(
                "INSERT INTO twitch_channels (ChannelName) VALUES (?)",
                ["leeksxy"]
            );
            console.log("Canal Twitch leeksxy adicionado ao monitoramento");
        } else {
            console.log("Canal Twitch leeksxy já está sendo monitorado");
        }

        await ensureWebhookConfigs(connection);
        console.log("Tabela webhook_configs criada/ajustada");

        await ensureCountingConfig(connection);
        console.log("Tabela counting_config criada/ajustada");

        console.log("Configuração do banco concluída!");
        return true;
    } catch (error) {
        console.error("Erro ao configurar banco:", error);
        return false;
    } finally {
        if (connection) {
            await connection.end().catch(() => {});
        }
    }
}

if (require.main === module) {
    setupDatabase();
}

module.exports = setupDatabase;
