const mysql = require("./mysql2-compat");
const path = require("path");

require("dotenv").config({ path: path.join(__dirname, "../../.env") });

async function columnExists(connection, tableName, columnName) {
    const [rows] = await connection.execute(`
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = ?
          AND column_name = ?
        LIMIT 1
    `, [tableName.toLowerCase(), columnName.toLowerCase()]);

    return rows.length > 0;
}

async function ensureColumn(connection, tableName, columnName, definition) {
    if (!(await columnExists(connection, tableName, columnName))) {
        await connection.execute(`ALTER TABLE ${tableName} ADD COLUMN ${columnName} ${definition}`);
    }
}

async function ensureRenamedColumn(connection, tableName, oldName, newName) {
    const hasOld = await columnExists(connection, tableName, oldName);
    const hasNew = await columnExists(connection, tableName, newName);

    if (hasOld && !hasNew) {
        await connection.execute(`ALTER TABLE ${tableName} RENAME COLUMN ${oldName} TO ${newName}`);
    }
}

async function ensureIdentity(connection, tableName, columnName = "id") {
    const [sequenceRows] = await connection.execute(
        "SELECT pg_get_serial_sequence(?, ?) AS seq",
        [tableName.toLowerCase(), columnName.toLowerCase()]
    );

    if (!sequenceRows[0]?.seq) {
        await connection.execute(`ALTER TABLE ${tableName} ALTER COLUMN ${columnName} ADD GENERATED BY DEFAULT AS IDENTITY`);
    }

    const [maxRows] = await connection.execute(
        `SELECT COALESCE(MAX(${columnName}), 0) AS max_id FROM ${tableName}`
    );
    const [updatedSequenceRows] = await connection.execute(
        "SELECT pg_get_serial_sequence(?, ?) AS seq",
        [tableName.toLowerCase(), columnName.toLowerCase()]
    );

    if (updatedSequenceRows[0]?.seq) {
        await connection.execute(
            "SELECT setval(?, ?, false)",
            [updatedSequenceRows[0].seq, Number(maxRows[0]?.max_id || 0) + 1]
        );
    }
}

async function ensureDefault(connection, tableName, columnName, defaultExpression) {
    await connection.execute(
        `ALTER TABLE ${tableName} ALTER COLUMN ${columnName} SET DEFAULT ${defaultExpression}`
    );
}

async function ensureBooleanColumn(connection, tableName, columnName, defaultValue = false) {
    await connection.execute(`
        ALTER TABLE ${tableName}
        ALTER COLUMN ${columnName} DROP DEFAULT
    `);
    await connection.execute(`
        ALTER TABLE ${tableName}
        ALTER COLUMN ${columnName} TYPE BOOLEAN
        USING CASE
            WHEN ${columnName} IS NULL THEN ${defaultValue ? "TRUE" : "FALSE"}
            WHEN ${columnName}::text IN ('1', 'true', 'TRUE', 't', 'T', 'yes', 'YES') THEN TRUE
            ELSE FALSE
        END
    `);
    await connection.execute(
        `UPDATE ${tableName} SET ${columnName} = ${defaultValue ? "TRUE" : "FALSE"} WHERE ${columnName} IS NULL`
    );
    await ensureDefault(connection, tableName, columnName, defaultValue ? "TRUE" : "FALSE");
}

async function ensureTimestampDefault(connection, tableName, columnName) {
    await connection.execute(
        `UPDATE ${tableName} SET ${columnName} = CURRENT_TIMESTAMP WHERE ${columnName} IS NULL`
    );
    await ensureDefault(connection, tableName, columnName, "CURRENT_TIMESTAMP");
}

async function ensureIntegerDefault(connection, tableName, columnName, defaultValue = 0) {
    await connection.execute(
        `UPDATE ${tableName} SET ${columnName} = ${defaultValue} WHERE ${columnName} IS NULL`
    );
    await ensureDefault(connection, tableName, columnName, String(defaultValue));
}

async function ensureIndex(connection, indexName, tableName, expression, unique = false) {
    await connection.execute(
        `CREATE ${unique ? "UNIQUE " : ""}INDEX IF NOT EXISTS ${indexName} ON ${tableName} (${expression})`
    );
}

async function ensureHistoricoprecos(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS historicoprecos (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            ProdutoId INT NOT NULL,
            Preco DECIMAL(10, 2) NOT NULL,
            PrecoAnterior DECIMAL(10, 2) DEFAULT NULL,
            DataRegisto TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            Loja VARCHAR(255),
            Status ENUM('Ativo', 'Inativo', 'Pausado') DEFAULT 'Ativo',
            Observacoes TEXT,
            FOREIGN KEY (ProdutoId) REFERENCES produtos(Id) ON DELETE CASCADE
        )
    `);

    await ensureIdentity(connection, "historicoprecos");
    await ensureColumn(connection, "historicoprecos", "PrecoAnterior", "NUMERIC(10, 2)");
    await ensureColumn(connection, "historicoprecos", "Loja", "VARCHAR(255)");
    await ensureColumn(connection, "historicoprecos", "Status", "VARCHAR(20) DEFAULT 'Ativo'");
    await ensureColumn(connection, "historicoprecos", "Observacoes", "TEXT");
    await ensureColumn(connection, "historicoprecos", "UpdatedAt", "TIMESTAMP");
    await ensureTimestampDefault(connection, "historicoprecos", "DataRegisto");
    await ensureTimestampDefault(connection, "historicoprecos", "UpdatedAt");
    await connection.execute("UPDATE historicoprecos SET Status = 'Ativo' WHERE Status IS NULL");
    await ensureDefault(connection, "historicoprecos", "Status", "'Ativo'");
    await ensureIndex(connection, "idx_historicoprecos_produto_data", "historicoprecos", "ProdutoId, DataRegisto");
    await ensureIndex(connection, "idx_historicoprecos_dataregisto", "historicoprecos", "DataRegisto");
    await ensureIndex(connection, "idx_historicoprecos_loja", "historicoprecos", "Loja");
}

async function ensureDiscordIdColumn(connection) {
    const [columns] = await connection.execute(`
        SELECT COLUMN_NAME
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'utilizadores'
          AND column_name = 'discord_id'
    `);

    if (columns.length === 0) {
        await connection.execute(`
            ALTER TABLE utilizadores
            ADD COLUMN discord_id VARCHAR(50) UNIQUE NULL
        `);
        console.log("Coluna discord_id adicionada a utilizadores");
    }
}

async function ensureTwitchChannels(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS twitch_channels (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            ChannelName VARCHAR(100) NOT NULL UNIQUE,
            TwitchUserId VARCHAR(50),
            IsLive BOOLEAN DEFAULT FALSE,
            LastLiveCheck TIMESTAMP NULL,
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "twitch_channels");
    await ensureColumn(connection, "twitch_channels", "TwitchUserId", "VARCHAR(50)");
    await ensureColumn(connection, "twitch_channels", "LastLiveCheck", "TIMESTAMP NULL");
    await ensureColumn(connection, "twitch_channels", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "twitch_channels", "UpdatedAt", "TIMESTAMP");
    await ensureBooleanColumn(connection, "twitch_channels", "IsLive", false);
    await ensureTimestampDefault(connection, "twitch_channels", "CreatedAt");
    await ensureTimestampDefault(connection, "twitch_channels", "UpdatedAt");
    await ensureIndex(connection, "idx_twitch_channels_channelname", "twitch_channels", "ChannelName");
    await ensureIndex(connection, "idx_twitch_channels_islive", "twitch_channels", "IsLive");
}

async function ensureWebhookConfigs(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS webhook_configs (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            Type ENUM('github', 'twitch', 'other') NOT NULL DEFAULT 'other',
            WebhookUrl VARCHAR(500),
            Secret VARCHAR(255),
            IsActive BOOLEAN DEFAULT TRUE,
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureRenamedColumn(connection, "webhook_configs", "tipo", "Type");
    await ensureIdentity(connection, "webhook_configs");
    await ensureColumn(connection, "webhook_configs", "Type", "VARCHAR(100) DEFAULT 'other'");
    await ensureColumn(connection, "webhook_configs", "WebhookUrl", "VARCHAR(500)");
    await ensureColumn(connection, "webhook_configs", "Secret", "VARCHAR(255)");
    await ensureColumn(connection, "webhook_configs", "IsActive", "BOOLEAN");
    await ensureColumn(connection, "webhook_configs", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "webhook_configs", "UpdatedAt", "TIMESTAMP");
    await connection.execute("UPDATE webhook_configs SET Type = 'other' WHERE Type IS NULL");
    await ensureDefault(connection, "webhook_configs", "Type", "'other'");
    await ensureBooleanColumn(connection, "webhook_configs", "IsActive", true);
    await ensureTimestampDefault(connection, "webhook_configs", "CreatedAt");
    await ensureTimestampDefault(connection, "webhook_configs", "UpdatedAt");
    await ensureIndex(connection, "idx_webhook_configs_type", "webhook_configs", "Type");
    await ensureIndex(connection, "idx_webhook_configs_isactive", "webhook_configs", "IsActive");
}

async function ensureCountingConfig(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS counting_config (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            GuildId VARCHAR(50) NOT NULL UNIQUE,
            ChannelId VARCHAR(50) NOT NULL,
            CurrentNumber INT DEFAULT 0,
            HighScore INT DEFAULT 0,
            LastUserId VARCHAR(50),
            LastMessageId VARCHAR(50),
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "counting_config");
    await ensureColumn(connection, "counting_config", "CurrentNumber", "INTEGER DEFAULT 0");
    await ensureColumn(connection, "counting_config", "HighScore", "INTEGER DEFAULT 0");
    await ensureColumn(connection, "counting_config", "LastUserId", "VARCHAR(50)");
    await ensureColumn(connection, "counting_config", "LastMessageId", "VARCHAR(50)");
    await ensureColumn(connection, "counting_config", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "counting_config", "UpdatedAt", "TIMESTAMP");
    await ensureIntegerDefault(connection, "counting_config", "CurrentNumber", 0);
    await ensureIntegerDefault(connection, "counting_config", "HighScore", 0);
    await ensureTimestampDefault(connection, "counting_config", "CreatedAt");
    await ensureTimestampDefault(connection, "counting_config", "UpdatedAt");
    await ensureIndex(connection, "idx_counting_config_guildid", "counting_config", "GuildId");
    await ensureIndex(connection, "idx_counting_config_channelid", "counting_config", "ChannelId");
}

async function ensureNewsConfig(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS news_config (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            ChannelId VARCHAR(50) NOT NULL,
            CheckInterval INT DEFAULT 60,
            MonitoredCategories TEXT,
            MinImpactScore INT DEFAULT 7,
            IsActive INT DEFAULT 1,
            LastCheck TIMESTAMP NULL,
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "news_config");
    await ensureColumn(connection, "news_config", "CheckInterval", "INTEGER DEFAULT 60");
    await ensureColumn(connection, "news_config", "MonitoredCategories", "TEXT");
    await ensureColumn(connection, "news_config", "MinImpactScore", "INTEGER DEFAULT 7");
    await ensureColumn(connection, "news_config", "IsActive", "INTEGER DEFAULT 1");
    await ensureColumn(connection, "news_config", "LastCheck", "TIMESTAMP NULL");
    await ensureColumn(connection, "news_config", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "news_config", "UpdatedAt", "TIMESTAMP");
    await ensureIntegerDefault(connection, "news_config", "CheckInterval", 60);
    await ensureIntegerDefault(connection, "news_config", "MinImpactScore", 7);
    await ensureIntegerDefault(connection, "news_config", "IsActive", 1);
    await ensureTimestampDefault(connection, "news_config", "CreatedAt");
    await ensureTimestampDefault(connection, "news_config", "UpdatedAt");
    await ensureIndex(connection, "idx_news_config_isactive", "news_config", "IsActive");
}

async function ensureReviews(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS reviews (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            ReferenciaID VARCHAR(13),
            discord_user_id VARCHAR(20),
            discord_username VARCHAR(100),
            discord_avatar_url VARCHAR(500),
            Tipo ENUM('site', 'bot', 'suporte') NOT NULL DEFAULT 'site',
            Texto TEXT NOT NULL,
            Rating INT,
            IsAnonimo INT DEFAULT 0,
            discord_channel_id VARCHAR(20),
            discord_message_id VARCHAR(20),
            SupportReferenciaID VARCHAR(13),
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "reviews");
    await ensureColumn(connection, "reviews", "ReferenciaID", "VARCHAR(13)");
    await ensureColumn(connection, "reviews", "discord_user_id", "VARCHAR(20)");
    await ensureColumn(connection, "reviews", "discord_username", "VARCHAR(100)");
    await ensureColumn(connection, "reviews", "discord_avatar_url", "VARCHAR(500)");
    await ensureColumn(connection, "reviews", "Tipo", "VARCHAR(20) DEFAULT 'site'");
    await ensureColumn(connection, "reviews", "Texto", "TEXT");
    await ensureColumn(connection, "reviews", "Rating", "INTEGER");
    await ensureColumn(connection, "reviews", "IsAnonimo", "INTEGER DEFAULT 0");
    await ensureColumn(connection, "reviews", "discord_channel_id", "VARCHAR(20)");
    await ensureColumn(connection, "reviews", "discord_message_id", "VARCHAR(20)");
    await ensureColumn(connection, "reviews", "SupportReferenciaID", "VARCHAR(13)");
    await ensureColumn(connection, "reviews", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "reviews", "UpdatedAt", "TIMESTAMP");
    await connection.execute("UPDATE reviews SET Tipo = 'site' WHERE Tipo IS NULL");
    await ensureDefault(connection, "reviews", "Tipo", "'site'");
    await ensureIntegerDefault(connection, "reviews", "IsAnonimo", 0);
    await ensureTimestampDefault(connection, "reviews", "CreatedAt");
    await ensureTimestampDefault(connection, "reviews", "UpdatedAt");
    await ensureIndex(connection, "idx_reviews_referenciaid", "reviews", "ReferenciaID");
    await ensureIndex(connection, "idx_reviews_discord_user_id", "reviews", "discord_user_id");
    await ensureIndex(connection, "idx_reviews_tipo", "reviews", "Tipo");
    await ensureIndex(connection, "idx_reviews_createdat", "reviews", "CreatedAt");
    await ensureIndex(connection, "idx_reviews_supportref", "reviews", "SupportReferenciaID");
}

async function ensureBugsProjetos(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS bugsprojetos (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            Titulo VARCHAR(200) NOT NULL,
            Descricao TEXT,
            Tipo ENUM('bug', 'projeto', 'melhoria') DEFAULT 'bug',
            Prioridade ENUM('low', 'medium', 'high', 'critical') DEFAULT 'medium',
            Status ENUM('open', 'in-progress', 'resolved', 'closed') DEFAULT 'open',
            CreatedBy VARCHAR(13),
            AnexoUrl VARCHAR(500),
            DataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            DataAtualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "bugsprojetos");
    await ensureColumn(connection, "bugsprojetos", "CreatedBy", "VARCHAR(13)");
    await ensureColumn(connection, "bugsprojetos", "AnexoUrl", "VARCHAR(500)");
    await ensureColumn(connection, "bugsprojetos", "DataCriacao", "TIMESTAMP");
    await ensureColumn(connection, "bugsprojetos", "DataAtualizacao", "TIMESTAMP");
    await ensureTimestampDefault(connection, "bugsprojetos", "DataCriacao");
    await ensureTimestampDefault(connection, "bugsprojetos", "DataAtualizacao");
    await ensureIndex(connection, "idx_bugs_status", "bugsprojetos", "Status");
    await ensureIndex(connection, "idx_bugs_tipo", "bugsprojetos", "Tipo");
    await ensureIndex(connection, "idx_bugs_createdby", "bugsprojetos", "CreatedBy");
    await ensureIndex(connection, "idx_bugs_datacriacao", "bugsprojetos", "DataCriacao");
}

async function ensureSugestoes(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS sugestoes (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            Titulo VARCHAR(200) NOT NULL,
            Descricao TEXT,
            Plataforma ENUM('site', 'bot', 'ambos') DEFAULT 'ambos',
            Prioridade ENUM('low', 'medium', 'high') DEFAULT 'medium',
            Status ENUM('pendente', 'em-analise', 'aprovada', 'em-desenvolvimento', 'implementada', 'rejeitada') DEFAULT 'pendente',
            Votos INT DEFAULT 0,
            DataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            DataAtualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "sugestoes");
    await ensureColumn(connection, "sugestoes", "Votos", "INTEGER DEFAULT 0");
    await ensureColumn(connection, "sugestoes", "DataCriacao", "TIMESTAMP");
    await ensureColumn(connection, "sugestoes", "DataAtualizacao", "TIMESTAMP");
    await ensureIntegerDefault(connection, "sugestoes", "Votos", 0);
    await ensureTimestampDefault(connection, "sugestoes", "DataCriacao");
    await ensureTimestampDefault(connection, "sugestoes", "DataAtualizacao");
    await ensureIndex(connection, "idx_sugestoes_status", "sugestoes", "Status");
    await ensureIndex(connection, "idx_sugestoes_plataforma", "sugestoes", "Plataforma");
    await ensureIndex(connection, "idx_sugestoes_datacriacao", "sugestoes", "DataCriacao");
}

async function ensureDiscordErrors(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS discord_errors (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            CommandName VARCHAR(100) NOT NULL,
            ErrorMessage TEXT NOT NULL,
            StackTrace TEXT,
            UserId VARCHAR(50),
            ChannelId VARCHAR(50),
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "discord_errors");
    await ensureColumn(connection, "discord_errors", "StackTrace", "TEXT");
    await ensureColumn(connection, "discord_errors", "UserId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_errors", "ChannelId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_errors", "CreatedAt", "TIMESTAMP");
    await ensureTimestampDefault(connection, "discord_errors", "CreatedAt");
    await ensureIndex(connection, "idx_discord_errors_command", "discord_errors", "CommandName");
    await ensureIndex(connection, "idx_discord_errors_createdat", "discord_errors", "CreatedAt");
}

async function ensureBirthdayTables(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS discord_birthdays (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            GuildId VARCHAR(50) NOT NULL,
            UserId VARCHAR(50) NOT NULL,
            BirthdayDate DATE NOT NULL,
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (GuildId, UserId)
        )
    `);

    await ensureIdentity(connection, "discord_birthdays");
    await ensureColumn(connection, "discord_birthdays", "GuildId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_birthdays", "UserId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_birthdays", "BirthdayDate", "DATE");
    await ensureColumn(connection, "discord_birthdays", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "discord_birthdays", "UpdatedAt", "TIMESTAMP");
    await ensureTimestampDefault(connection, "discord_birthdays", "CreatedAt");
    await ensureTimestampDefault(connection, "discord_birthdays", "UpdatedAt");
    await ensureIndex(connection, "idx_discord_birthdays_guild_user", "discord_birthdays", "GuildId, UserId", true);
    await ensureIndex(connection, "idx_discord_birthdays_date", "discord_birthdays", "BirthdayDate");

    await connection.execute(`
        CREATE TABLE IF NOT EXISTS discord_birthday_settings (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            GuildId VARCHAR(50) NOT NULL UNIQUE,
            Enabled BOOLEAN DEFAULT FALSE,
            ChannelId VARCHAR(50),
            RoleId VARCHAR(50),
            MessageTemplate VARCHAR(220) DEFAULT 'Happy Birthday, {user}!',
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "discord_birthday_settings");
    await ensureColumn(connection, "discord_birthday_settings", "GuildId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_birthday_settings", "Enabled", "BOOLEAN");
    await ensureColumn(connection, "discord_birthday_settings", "ChannelId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_birthday_settings", "RoleId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_birthday_settings", "MessageTemplate", "VARCHAR(220) DEFAULT 'Happy Birthday, {user}!'");
    await ensureColumn(connection, "discord_birthday_settings", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "discord_birthday_settings", "UpdatedAt", "TIMESTAMP");
    await ensureBooleanColumn(connection, "discord_birthday_settings", "Enabled", false);
    await ensureTimestampDefault(connection, "discord_birthday_settings", "CreatedAt");
    await ensureTimestampDefault(connection, "discord_birthday_settings", "UpdatedAt");
    await ensureIndex(connection, "idx_discord_birthday_settings_guild", "discord_birthday_settings", "GuildId", true);
}

async function ensureYoutubeFeedChannels(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS youtube_feed_channels (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            YoutubeChannelId VARCHAR(100) NOT NULL,
            DiscordChannelId VARCHAR(50) NOT NULL,
            PingEveryone BOOLEAN DEFAULT FALSE,
            LastVideoId VARCHAR(255),
            IsActive BOOLEAN DEFAULT TRUE,
            LastCheckedAt TIMESTAMP NULL,
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (YoutubeChannelId, DiscordChannelId)
        )
    `);

    await ensureIdentity(connection, "youtube_feed_channels");
    await ensureColumn(connection, "youtube_feed_channels", "YoutubeChannelId", "VARCHAR(100)");
    await ensureColumn(connection, "youtube_feed_channels", "DiscordChannelId", "VARCHAR(50)");
    await ensureColumn(connection, "youtube_feed_channels", "PingEveryone", "BOOLEAN");
    await ensureColumn(connection, "youtube_feed_channels", "LastVideoId", "VARCHAR(255)");
    await ensureColumn(connection, "youtube_feed_channels", "IsActive", "BOOLEAN");
    await ensureColumn(connection, "youtube_feed_channels", "LastCheckedAt", "TIMESTAMP NULL");
    await ensureColumn(connection, "youtube_feed_channels", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "youtube_feed_channels", "UpdatedAt", "TIMESTAMP");
    await ensureBooleanColumn(connection, "youtube_feed_channels", "PingEveryone", false);
    await ensureBooleanColumn(connection, "youtube_feed_channels", "IsActive", true);
    await ensureTimestampDefault(connection, "youtube_feed_channels", "CreatedAt");
    await ensureTimestampDefault(connection, "youtube_feed_channels", "UpdatedAt");
    await ensureIndex(connection, "idx_youtube_feed_active", "youtube_feed_channels", "IsActive");
    await ensureIndex(connection, "idx_youtube_feed_discord_channel", "youtube_feed_channels", "DiscordChannelId");
    await ensureIndex(connection, "idx_youtube_feed_unique", "youtube_feed_channels", "YoutubeChannelId, DiscordChannelId", true);
}

async function ensureDiscordGuildSettings(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS discord_guild_settings (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            GuildId VARCHAR(50) NOT NULL UNIQUE,
            Prefix VARCHAR(5) NOT NULL DEFAULT '!',
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "discord_guild_settings");
    await ensureColumn(connection, "discord_guild_settings", "GuildId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_guild_settings", "Prefix", "VARCHAR(5) DEFAULT '!'");
    await ensureColumn(connection, "discord_guild_settings", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "discord_guild_settings", "UpdatedAt", "TIMESTAMP");
    await connection.execute("UPDATE discord_guild_settings SET Prefix = '!' WHERE Prefix IS NULL OR Prefix = ''");
    await ensureDefault(connection, "discord_guild_settings", "Prefix", "'!'");
    await ensureTimestampDefault(connection, "discord_guild_settings", "CreatedAt");
    await ensureTimestampDefault(connection, "discord_guild_settings", "UpdatedAt");
    await ensureIndex(connection, "idx_discord_guild_settings_guild", "discord_guild_settings", "GuildId", true);
}

async function ensureWelcomeConfig(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS discord_welcome_settings (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            GuildId VARCHAR(50) NOT NULL UNIQUE,
            Enabled BOOLEAN DEFAULT FALSE,
            ChannelId VARCHAR(50),
            MessageTemplate VARCHAR(500) DEFAULT 'Bem-vindo(a) {user} a {guild}!',
            AutoRoleId VARCHAR(50),
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "discord_welcome_settings");
    await ensureColumn(connection, "discord_welcome_settings", "GuildId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_welcome_settings", "Enabled", "BOOLEAN");
    await ensureColumn(connection, "discord_welcome_settings", "ChannelId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_welcome_settings", "MessageTemplate", "VARCHAR(500) DEFAULT 'Bem-vindo(a) {user} a {guild}!'");
    await ensureColumn(connection, "discord_welcome_settings", "AutoRoleId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_welcome_settings", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "discord_welcome_settings", "UpdatedAt", "TIMESTAMP");
    await ensureBooleanColumn(connection, "discord_welcome_settings", "Enabled", false);
    await ensureTimestampDefault(connection, "discord_welcome_settings", "CreatedAt");
    await ensureTimestampDefault(connection, "discord_welcome_settings", "UpdatedAt");
    await ensureIndex(connection, "idx_discord_welcome_settings_guild", "discord_welcome_settings", "GuildId", true);
}

async function ensureVerificationConfig(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS discord_verification_settings (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            GuildId VARCHAR(50) NOT NULL UNIQUE,
            Enabled BOOLEAN DEFAULT FALSE,
            ChannelId VARCHAR(50),
            RoleId VARCHAR(50),
            MessageId VARCHAR(50),
            MessageText VARCHAR(700) DEFAULT 'Clica no botão abaixo para receber acesso ao servidor.',
            ButtonLabel VARCHAR(80) DEFAULT 'Verificar',
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "discord_verification_settings");
    await ensureColumn(connection, "discord_verification_settings", "GuildId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_verification_settings", "Enabled", "BOOLEAN");
    await ensureColumn(connection, "discord_verification_settings", "ChannelId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_verification_settings", "RoleId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_verification_settings", "MessageId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_verification_settings", "MessageText", "VARCHAR(700) DEFAULT 'Clica no botão abaixo para receber acesso ao servidor.'");
    await ensureColumn(connection, "discord_verification_settings", "ButtonLabel", "VARCHAR(80) DEFAULT 'Verificar'");
    await ensureColumn(connection, "discord_verification_settings", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "discord_verification_settings", "UpdatedAt", "TIMESTAMP");
    await ensureBooleanColumn(connection, "discord_verification_settings", "Enabled", false);
    await ensureTimestampDefault(connection, "discord_verification_settings", "CreatedAt");
    await ensureTimestampDefault(connection, "discord_verification_settings", "UpdatedAt");
    await ensureIndex(connection, "idx_discord_verification_settings_guild", "discord_verification_settings", "GuildId", true);
}

async function ensureDiscordGiveaways(connection) {
    await connection.execute(`
        CREATE TABLE IF NOT EXISTS discord_giveaways (
            Id INT AUTO_INCREMENT PRIMARY KEY,
            GuildId VARCHAR(50) NOT NULL,
            ChannelId VARCHAR(50) NOT NULL,
            MessageId VARCHAR(50) NOT NULL UNIQUE,
            HostUserId VARCHAR(50) NOT NULL,
            Prize VARCHAR(255) NOT NULL,
            WinnerCount INT DEFAULT 1,
            ReactionEmoji VARCHAR(32) DEFAULT '🎉',
            EndsAt TIMESTAMP NOT NULL,
            Ended BOOLEAN DEFAULT FALSE,
            WinnerIds TEXT,
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await ensureIdentity(connection, "discord_giveaways");
    await ensureColumn(connection, "discord_giveaways", "GuildId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_giveaways", "ChannelId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_giveaways", "MessageId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_giveaways", "HostUserId", "VARCHAR(50)");
    await ensureColumn(connection, "discord_giveaways", "Prize", "VARCHAR(255)");
    await ensureColumn(connection, "discord_giveaways", "WinnerCount", "INTEGER DEFAULT 1");
    await ensureColumn(connection, "discord_giveaways", "ReactionEmoji", "VARCHAR(32) DEFAULT '🎉'");
    await ensureColumn(connection, "discord_giveaways", "EndsAt", "TIMESTAMP");
    await ensureColumn(connection, "discord_giveaways", "Ended", "BOOLEAN");
    await ensureColumn(connection, "discord_giveaways", "WinnerIds", "TEXT");
    await ensureColumn(connection, "discord_giveaways", "CreatedAt", "TIMESTAMP");
    await ensureColumn(connection, "discord_giveaways", "UpdatedAt", "TIMESTAMP");
    await ensureBooleanColumn(connection, "discord_giveaways", "Ended", false);
    await ensureIntegerDefault(connection, "discord_giveaways", "WinnerCount", 1);
    await ensureTimestampDefault(connection, "discord_giveaways", "CreatedAt");
    await ensureTimestampDefault(connection, "discord_giveaways", "UpdatedAt");
    await ensureIndex(connection, "idx_discord_giveaways_message", "discord_giveaways", "MessageId", true);
    await ensureIndex(connection, "idx_discord_giveaways_guild", "discord_giveaways", "GuildId");
    await ensureIndex(connection, "idx_discord_giveaways_pending", "discord_giveaways", "Ended, EndsAt");
}

async function setupDatabase() {
    console.log("Configurando banco de dados para Discord Bot...");

    const dbConfig = {
        host: process.env.DB_HOST || "localhost",
        user: process.env.DB_USER || "postgres",
        password: process.env.DB_PASSWORD || "",
        database: process.env.DB_NAME || "papv5",
        port: parseInt(process.env.DB_PORT, 10) || 5432,
    };

    let connection;

    try {
        connection = await mysql.createConnection(dbConfig);
        console.log("Conectado ao banco de dados");

        await ensureHistoricoprecos(connection);
        console.log("Tabela historicoprecos criada/ajustada");

        await ensureDiscordIdColumn(connection);
        await ensureTwitchChannels(connection);
        console.log("Tabela twitch_channels criada/ajustada");

        await ensureWebhookConfigs(connection);
        console.log("Tabela webhook_configs criada/ajustada");

        await ensureCountingConfig(connection);
        console.log("Tabela counting_config criada/ajustada");

        await ensureNewsConfig(connection);
        console.log("Tabela news_config criada/ajustada");

        await ensureReviews(connection);
        console.log("Tabela reviews criada/ajustada");

        await ensureBugsProjetos(connection);
        console.log("Tabela bugsprojetos criada/ajustada");

        await ensureSugestoes(connection);
        console.log("Tabela sugestoes criada/ajustada");

        await ensureDiscordErrors(connection);
        console.log("Tabela discord_errors criada/ajustada");

        await ensureBirthdayTables(connection);
        console.log("Tabelas de birthday criadas/ajustadas");

        await ensureYoutubeFeedChannels(connection);
        console.log("Tabela youtube_feed_channels criada/ajustada");

        await ensureDiscordGuildSettings(connection);
        console.log("Tabela discord_guild_settings criada/ajustada");

        await ensureWelcomeConfig(connection);
        console.log("Tabela discord_welcome_settings criada/ajustada");

        await ensureVerificationConfig(connection);
        console.log("Tabela discord_verification_settings criada/ajustada");

        await ensureDiscordGiveaways(connection);
        console.log("Tabela discord_giveaways criada/ajustada");

        console.log("Configuracao do banco concluida");
        return true;
    } catch (error) {
        console.error("Erro ao configurar banco:", error);
        return false;
    } finally {
        if (connection) {
            await connection.end().catch(() => {});
        }
    }
}

if (require.main === module) {
    setupDatabase();
}

module.exports = setupDatabase;
